import type { Source } from "./types";

export const SOURCES: Source[] = [
  {
    id: "cygx1",
    name: "Cygnus X-1",
    massSolar: 21.2,
    spin: 0.97,
    inclinationDeg: 27,
    archive: "RXTE PCA · 16 yr",
    note: "Best-constrained inclination. IXPE hard-state PD = 4.01% — twice compact-corona prediction.",
    contradictions: [2, 3],
  },
  {
    id: "grs1915",
    name: "GRS 1915+105",
    massSolar: 12.4,
    spin: 0.98,
    inclinationDeg: 66,
    archive: "RXTE PCA",
    note: "Twelve variability classes. Heartbeat (ρ) unreproduced by GRMHD. Closest ML predecessor: Orwat-Kapola 2022, one source.",
    contradictions: [7, 4],
  },
  {
    id: "gx339",
    name: "GX 339-4",
    massSolar: 9.0,
    spin: 0.93,
    inclinationDeg: 40,
    archive: "RXTE + XMM",
    note: "Canonical q-diagram hysteresis. Multiple outburst cycles.",
    contradictions: [5, 3],
  },
  {
    id: "j1550",
    name: "XTE J1550-564",
    massSolar: 9.1,
    spin: 0.84,
    inclinationDeg: 75,
    archive: "RXTE",
    note: "Classic outburst. Strong Type-C → Type-B sequence.",
    contradictions: [1, 5],
  },
  {
    id: "gro1655",
    name: "GRO J1655-40",
    massSolar: 6.3,
    spin: 0.7,
    inclinationDeg: 70,
    archive: "RXTE",
    note: "High-inclination microquasar. Jet + QPO laboratory.",
    contradictions: [6, 1],
  },
  {
    id: "h1743",
    name: "H1743-322",
    massSolar: 8.0,
    spin: 0.2,
    inclinationDeg: 75,
    archive: "RXTE",
    note: "Predicted Γ modulation from LT precession not statistically significant.",
    contradictions: [1, 4],
  },
  {
    id: "u1630",
    name: "4U 1630-47",
    massSolar: 10.0,
    spin: 0.9,
    inclinationDeg: 65,
    archive: "RXTE",
    note: "QPO → heartbeat transition in <1 day. Second system after GRS 1915.",
    contradictions: [7, 5],
  },
  {
    id: "j1820",
    name: "MAXI J1820+070",
    massSolar: 8.5,
    spin: 0.2,
    inclinationDeg: 63,
    archive: "NICER + MAXI",
    note: "Calibration benchmark. Unusual but published (Bellavita 2025, Ma 2021, Buisson 2021). Every flag is asked: J1820-like or new?",
    contradictions: [1, 4, 5],
  },
  {
    id: "j1727",
    name: "Swift J1727.8-1613",
    massSolar: 10.0,
    spin: 0.6,
    inclinationDeg: 40,
    archive: "IXPE + NICER 2023–24",
    note: "QPO polarization crisis: 1.34 Hz, 12.3% rms, Γ modulates, PD/PA do not. Jet–QPO coincidence to tens of minutes.",
    contradictions: [1, 6, 3],
  },
];

export const SOURCE_BY_ID = Object.fromEntries(SOURCES.map((s) => [s.id, s])) as Record<
  Source["id"],
  Source
>;
